"""End-to-end agent entry point.

Usage:
    uv run python agent.py --ticket fixtures/ticket_1.json
"""

import argparse
import sys

import config
from src.agent_loop import AgentLoop
from src.github_client import GitHubAppClient, build_pr_body
from src.repo_context import RepoContext
from src.ticket_reader import load_ticket


def main():
    parser = argparse.ArgumentParser(
        description="Run the AI engineering agent on a ticket."
    )
    parser.add_argument(
        "--ticket",
        required=True,
        help="Path to a ticket JSON file (e.g. fixtures/ticket_1.json)",
    )
    parser.add_argument(
        "--max-attempts",
        type=int,
        default=3,
        help="Max generate→validate→retry attempts before giving up.",
    )
    parser.add_argument(
        "--no-pr",
        action="store_true",
        help="Skip opening a PR (just run the agent loop locally).",
    )
    args = parser.parse_args()

    config.validate()

    # 1. Load ticket
    ticket = load_ticket(args.ticket)
    print(f"🎫 Loaded ticket: {ticket.key} — {ticket.summary}")

    # 2. Run the agent loop
    repo_ctx = RepoContext(config.SANDBOX_REPO, config.WORK_DIR)
    loop = AgentLoop(ticket=ticket, repo_ctx=repo_ctx, max_attempts=args.max_attempts)
    result = loop.run()

    # 3. Decide whether to open a PR
    if not result.success:
        print("\n❌ Agent failed all attempts. Skipping PR.")
        print(
            "   Consider: increasing --max-attempts, refining the ticket, or escalating to a human."
        )
        sys.exit(1)

    if args.no_pr:
        print("\n--no-pr passed — skipping PR creation.")
        sys.exit(0)

    # 4. Push branch + open draft PR
    print("\n" + "=" * 60)
    print("📤 Pushing changes and opening draft PR...")
    print("=" * 60)

    gh = GitHubAppClient()
    branch_name = f"ai-agent/{ticket.key.lower()}"
    commit_message = f"[{ticket.key}] {ticket.summary}\n\nGenerated by 365-PDLC-Agent."

    gh.push_branch_with_changes(
        local_repo_path=repo_ctx.local_path,
        branch_name=branch_name,
        commit_message=commit_message,
    )

    pr = gh.open_draft_pr(
        branch_name=branch_name,
        title=f"[{ticket.key}] {ticket.summary}",
        body=build_pr_body(ticket, result),
    )

    print(f"\n✅ Draft PR opened: {pr['html_url']}")


if __name__ == "__main__":
    main()
