"""HTTP wrapper around the agent. Power Automate calls this.

Run locally:
    uv run uvicorn api:app --reload --port 8000

Then POST a ticket payload to: http://localhost:8000/process-ticket
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

import config
from src.agent_loop import AgentLoop
from src.github_client import GitHubAppClient, build_pr_body
from src.repo_context import RepoContext
from src.ticket_reader import Ticket


app = FastAPI(title="365-PDLC-Agent API", version="0.1.0")


class TicketPayload(BaseModel):
    """Incoming ticket from Jira (or Power Automate, or curl)."""

    key: str = Field(..., description="Ticket key, e.g. KAN-1")
    summary: str
    description: str
    acceptance_criteria: list[str] = Field(default_factory=list)
    labels: list[str] = Field(default_factory=list)
    target_files_hint: Optional[list[str]] = None


class AgentResponse(BaseModel):
    """What we return to the caller."""

    success: bool
    attempts: int
    pr_url: Optional[str] = None
    branch: Optional[str] = None
    reasoning: list[str] = Field(default_factory=list)
    validation_summary: list[str] = Field(default_factory=list)
    message: str


@app.get("/health")
def health():
    """Simple health check Power Automate or a load balancer can ping."""
    return {"status": "ok", "service": "365-PDLC-Agent"}


@app.post("/process-ticket", response_model=AgentResponse)
def process_ticket(payload: TicketPayload):
    """Main endpoint: run the agent on a ticket and return the outcome."""
    try:
        config.validate()
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=f"Server misconfigured: {e}")

    ticket = Ticket(**payload.model_dump())

    repo_ctx = RepoContext(config.SANDBOX_REPO, config.WORK_DIR)
    loop = AgentLoop(ticket=ticket, repo_ctx=repo_ctx, max_attempts=3)
    result = loop.run()

    validation_lines = [
        f"{'✅' if r.passed else '❌'} {r.name}" for r in result.final_validation
    ]

    # Outcome 1: BLOCKED (policy)
    if result.blocked:
        return AgentResponse(
            success=False,
            blocked=True,
            block_reason=result.block_reason,
            attempts=result.attempts,
            reasoning=result.reasoning_log,
            validation_summary=validation_lines,
            message=f"🛑 Blocked: {result.block_reason}",
        )

    # Outcome 2: FAILED (validation failed all attempts)
    if not result.success:
        return AgentResponse(
            success=False,
            attempts=result.attempts,
            reasoning=result.reasoning_log,
            validation_summary=validation_lines,
            message=f"Agent failed after {result.attempts} attempts. No PR created.",
        )

    # Outcome 3: SUCCESS — push branch + open draft PR
    try:
        gh = GitHubAppClient()
        branch_name = f"ai-agent/{ticket.key.lower()}"
        commit_message = (
            f"[{ticket.key}] {ticket.summary}\n\nGenerated by 365-PDLC-Agent."
        )

        gh.push_branch_with_changes(
            local_repo_path=repo_ctx.local_path,
            branch_name=branch_name,
            commit_message=commit_message,
        )
        pr = gh.open_draft_pr(
            branch_name=branch_name,
            title=f"[{ticket.key}] {ticket.summary}",
            body=build_pr_body(ticket, result),
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GitHub push/PR failed: {e}")

    return AgentResponse(
        success=True,
        attempts=result.attempts,
        pr_url=pr["html_url"],
        branch=branch_name,
        reasoning=result.reasoning_log,
        validation_summary=validation_lines,
        message=f"Draft PR opened after {result.attempts} attempt(s).",
    )
